/**
 * 外挂字幕序列化(P11)—— CaptionTrack → SRT / WebVTT 文本。
 *
 * SRT:序号 + `HH:MM:SS,mmm --> HH:MM:SS,mmm`(逗号毫秒,CRLF 行尾,规范口径)。
 * WebVTT:`WEBVTT` 头 + `HH:MM:SS.mmm`(点毫秒,LF)。
 * 携带说话人时以 `[陈默]` 前缀行内标注(双行字幕/样式 = 扩展位)。
 */
import type { CaptionCue, CaptionTrack } from './compile';
import type { KaraokeLine } from './karaoke';

const pad = (n: number, w = 2): string => String(n).padStart(w, '0');

const clock = (ms: number, sep: ',' | '.'): string => {
  const total = Math.max(0, Math.round(ms));
  const h = Math.floor(total / 3_600_000);
  const m = Math.floor((total % 3_600_000) / 60_000);
  const s = Math.floor((total % 60_000) / 1000);
  const mmm = total % 1000;
  return `${pad(h)}:${pad(m)}:${pad(s)}${sep}${pad(mmm, 3)}`;
};

const cueText = (c: CaptionCue): string =>
  c.character ? `[${c.character}]${c.text}` : c.text;

/** SubRip(SRT):CRLF 行尾 + 逗号毫秒(规范口径)。 */
export const toSrt = (track: CaptionTrack): string =>
  track.captions
    .map((c, i) =>
      [
        String(i + 1),
        `${clock(c.startMs, ',')} --> ${clock(c.endMs, ',')}`,
        cueText(c),
      ].join('\r\n'),
    )
    .join('\r\n\r\n') + (track.captions.length ? '\r\n' : '');

/** WebVTT:WEBVTT 头 + 点毫秒(LF;cue 间空行,规范口径)。 */
export const toVtt = (track: CaptionTrack): string => {
  const blocks = track.captions.map((c, i) =>
    [
      String(i + 1),
      `${clock(c.startMs, '.')} --> ${clock(c.endMs, '.')}`,
      cueText(c),
    ].join('\n'),
  );
  return ['WEBVTT', '', blocks.join('\n\n')].join('\n') + (blocks.length ? '\n' : '');
};


// ── ASS(P14:卡拉OK \k 逐词着色 + 普通轨) ─────────────────────────────────

const assTime = (ms: number): string => {
  const total = Math.max(0, Math.round(ms));
  const h = Math.floor(total / 3_600_000);
  const m = Math.floor((total % 3_600_000) / 60_000);
  const s = Math.floor((total % 60_000) / 1000);
  const cs = Math.floor((total % 1000) / 10);
  return `${h}:${pad(m)}:${pad(s)}.${pad(cs)}`;
};

/** ASS 文本安全:花括号是 override 块语法,替换为全角(词形 token 天然无花括号)。 */
const assText = (s: string): string => s.replace(/[{}]/g, '');

export interface AssOptions {
  playResX?: number;
  playResY?: number;
  font?: string;
  title?: string;
}

const assHeader = (opts: AssOptions): string[] => [
  '[Script Info]',
  '; Generated by StoryFlowIR',
  `Title: ${opts.title ?? 'StoryFlow Captions'}`,
  'ScriptType: v4.00+',
  `PlayResX: ${opts.playResX ?? 1920}`,
  `PlayResY: ${opts.playResY ?? 1080}`,
  'WrapStyle: 0',
  'ScaledBorderAndShadow: yes',
  '',
  '[V4+ Styles]',
  'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
  `Style: Default,${opts.font ?? 'Arial'},60,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,-1,0,0,0,100,100,0,0,1,2,1,2,60,60,40,1`,
  '',
  '[Events]',
  'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
];

/** 行组装(text 需调用侧保证 ASS 安全:纯文本先过 assText;\k override 块不过)。 */
const dialogueLine = (startMs: number, endMs: number, name: string, text: string): string =>
  `Dialogue: 0,${assTime(startMs)},${assTime(endMs)},Default,${name},0,0,0,,${text}`;

/** 卡拉OK ASS:逐词 `{\kN}`(厘秒;词间空隙折入前词高亮),说话人入 Name 字段。 */
export const toAssKaraoke = (
  lines: KaraokeLine[],
  opts: AssOptions = {},
): string => {
  const events = lines.map(l => {
    const parts = l.words.map((w, i) => {
      const nextStart = i + 1 < l.words.length ? l.words[i + 1].startMs : l.endMs;
      const durCs = Math.max(0, Math.round((nextStart - w.startMs) / 10));
      let text = w.text;
      if (i + 1 < l.words.length) {
        const next = l.words[i + 1].text;
        if (/\w$/.test(text) && /^\w/.test(next)) text += ' ';
      }
      return `{\\k${durCs}}${text}`;
    });
    return dialogueLine(l.startMs, l.endMs, l.character ?? '', parts.join(''));
  });
  // 尾随换行恒有(文件格式惯例;空轨 = 仅头)
  return [...assHeader(opts), ...events].join('\n') + '\n';
};

/** 普通 ASS(P11 CaptionTrack 直转,无 \k)。 */
export const toAss = (track: CaptionTrack, opts: AssOptions = {}): string => {
  const events = track.captions.map(c =>
    dialogueLine(c.startMs, c.endMs, c.character ?? '', assText(cueText(c))),
  );
  // 尾随换行恒有(文件格式惯例;空轨 = 仅头)
  return [...assHeader(opts), ...events].join('\n') + '\n';
};
